services:
  - name: spotirank-backend
    env: python3
    buildCommand: pip3 install -r requirements.txt
    startCommand: gunicorn -b :$PORT server:app

  - name: spotirank-frontend
    buildCommand: npm run build
    staticPublishPath: dist